In [1]:
import pandas as pd
import numpy as np

1. Create a Pandas DataFrame reading N rows of the 'data_000637.txt' dataset. Choose N to be smaller than or equal to the maximum number of rows and larger that 10k.

In [14]:
file_name='~/LaboratoryOfComputationalPhysics_Y6/Ex06/data_000637.txt'
data=pd.read_csv(file_name)
rows,_=data.shape
print("Rows:",rows)

N=np.random.randint(10000,rows)

data=data.head(N)
data

Rows: 1310720

        HEAD  FPGA  TDC_CHANNEL   ORBIT_CNT  BX_COUNTER  TDC_MEAS
0          1     0          123  3869200167        2374        26
1          1     0          124  3869200167        2374        27
2          1     0           63  3869200167        2553        28
3          1     0           64  3869200167        2558        19
4          1     0           64  3869200167        2760        25
...      ...   ...          ...         ...         ...       ...
114129     1     0           64  3869201301        3136         8
114130     1     1            3  3869201301        3299         7
114131     1     0           45  3869201301        3301        21
114132     1     1            4  3869201301        3299        20
114133     1     0           46  3869201301        3299        28

[114134 rows x 6 columns]